In [ ]:
import torch
import numpy as np

###Реализация функции Convolution Transpose (транспорнированной 2D свёртка)

In [46]:
def conv_transpose(input, weight, bias = None, stride = 1, padding = 0, output_padding = 0, groups = 1, dilation = 1):

    #нахождение размеров изображения и ядра
    batch_size, in_channels, in_height, in_width = input.shape
    out_channels, in_channels, kernel_height, kernel_width = weight.shape

    #нахождение размеров результирующего тензора
    out_height = (in_height - 1) * stride - 2 * padding + kernel_height + output_padding
    out_width = (in_width - 1) * stride - 2 * padding + kernel_width + output_padding
    output = np.zeros((batch_size, out_channels, out_height, out_width))

    #проход ядром по тензору
    for b in range(batch_size):
        for c in range(out_channels):
            for i in range(out_height):
                for j in range(out_width):
                    for k in range(in_channels):
                        for s in range(kernel_height):
                            for t in range(kernel_width):
                                ii = i + padding - s * dilation
                                jj = j + padding - t * dilation
                                if ii >= 0 and jj >= 0 and ii < in_height * stride and jj < in_width * stride and (ii % stride == 0) and (jj % stride == 0):
                                    ii //= stride
                                    jj //= stride
                                    output[b, c, i, j] += input[b, k, ii, jj] * weight[c, k, s, t]

            #по каналам и батчам добавляем смещение
            if bias is not None:
                output[b, c, :, :] += bias[c]
    return output

###Тест 1

In [50]:
input_data = torch.randn(1, 1, 3, 3)
kernel = torch.randn(1, 1, 3, 3)

#результат использования нашей функции conv_transpose
our_result1 = conv_transpose(input_data.numpy(), kernel.numpy())
print("Результат использования нашей функции conv_transpose в тесте 1:")
print(our_result1)
torch_result1 = torch.nn.functional.conv_transpose2d(input_data, kernel).numpy()
print("\nРезультат использования функции conv_transpose2d библиотеки PyTorch в тесте 1:")
print(torch_result1)

Результат использования нашей функции conv_transpose в тесте 1:
[[[[-2.24578023 -4.33491832  1.12922537  2.54033005 -0.73261225]
   [ 0.11532092  3.18368217 -2.25279398 -0.9965588   1.63676402]
   [ 7.77387619  1.882065   -3.70488552  0.07098394  1.38933391]
   [-0.70864844 -0.87236714  2.11897575 -2.25038504 -1.25848893]
   [-1.53664243  2.48185635  1.04869038 -1.54189283 -0.59790146]]]]

Результат использования функции conv_transpose2d библиотеки PyTorch в тесте 1:
[[[[-2.2457802  -4.3349185   1.1292254   2.54033    -0.73261225]
   [ 0.11532092  3.1836822  -2.252794   -0.9965588   1.636764  ]
   [ 7.773876    1.882065   -3.704886    0.07098395  1.389334  ]
   [-0.70864844 -0.87236714  2.1189756  -2.250385   -1.2584889 ]
   [-1.5366424   2.4818563   1.0486903  -1.5418928  -0.59790146]]]]


###Тест 2

In [51]:
input_data = torch.randn(1, 1, 3, 3)
kernel = torch.randn(1, 1, 3, 3)

#результат использования нашей функции conv_transpose
our_result2 = conv_transpose(input_data.numpy(), kernel.numpy())
print("Результат использования нашей функции conv_transpose в тесте 2:")
print(our_result2)
torch_result2 = torch.nn.functional.conv_transpose2d(input_data, kernel).numpy()
print("\nРезультат использования функции conv_transpose2d библиотеки PyTorch в тесте 2:")
print(torch_result2)

Результат использования нашей функции conv_transpose в тесте 2:
[[[[ 4.37069505e-01  2.04331493e+00  2.36251839e+00  7.86548853e-02
    -1.42741203e-01]
   [-1.32733382e+00 -2.61703885e+00 -3.85363430e-01 -5.94876617e-01
     3.75289634e-01]
   [-7.01490775e-01 -4.03692688e+00 -2.86256826e+00  1.08673556e-01
    -2.76908268e-01]
   [ 1.10066546e+00  1.32203570e+00 -1.79108575e+00  5.68660529e-01
     3.87719083e-02]
   [-1.62573785e-01  6.54389977e-01  1.18848924e+00  3.67412502e-02
    -3.19067709e-04]]]]

Результат использования функции conv_transpose2d библиотеки PyTorch в тесте 2:
[[[[ 4.37069505e-01  2.04331493e+00  2.36251831e+00  7.86548853e-02
    -1.42741203e-01]
   [-1.32733381e+00 -2.61703897e+00 -3.85363400e-01 -5.94876647e-01
     3.75289619e-01]
   [-7.01490760e-01 -4.03692675e+00 -2.86256814e+00  1.08673535e-01
    -2.76908278e-01]
   [ 1.10066545e+00  1.32203579e+00 -1.79108572e+00  5.68660498e-01
     3.87719087e-02]
   [-1.62573785e-01  6.54389977e-01  1.18848920e+00 

###Тест 3

In [52]:
input_data = torch.randn(1, 1, 3, 3)
kernel = torch.randn(1, 1, 3, 3)

#результат использования нашей функции conv_transpose
our_result3 = conv_transpose(input_data.numpy(), kernel.numpy())
print("Результат использования нашей функции conv_transpose в тесте 3:")
print(our_result3)
torch_result3 = torch.nn.functional.conv_transpose2d(input_data, kernel).numpy()
print("\nРезультат использования функции conv_transpose2d библиотеки PyTorch в тесте 3:")
print(torch_result3)

Результат использования нашей функции conv_transpose в тесте 3:
[[[[-7.19591618e-01  8.73012945e-01  1.81433323e+00 -1.69575940e+00
    -7.51717448e-01]
   [ 1.16713384e+00  1.30789648e+00 -4.54038842e+00 -2.47882971e+00
     2.83663046e+00]
   [-1.06749803e-01 -1.86700706e+00  1.67162266e+00  1.51970905e+00
    -1.25779215e+00]
   [-5.68770856e-01 -1.64393098e+00  2.46706977e-03 -5.34820162e-01
     5.97156867e-01]
   [ 7.21489310e-01 -8.56392607e-02  4.15331200e-01 -7.52089703e-02
     4.01260369e-02]]]]

Результат использования функции conv_transpose2d библиотеки PyTorch в тесте 3:
[[[[-7.1959162e-01  8.7301296e-01  1.8143333e+00 -1.6957594e+00
    -7.5171745e-01]
   [ 1.1671338e+00  1.3078965e+00 -4.5403886e+00 -2.4788299e+00
     2.8366303e+00]
   [-1.0674980e-01 -1.8670070e+00  1.6716226e+00  1.5197091e+00
    -1.2577922e+00]
   [-5.6877089e-01 -1.6439310e+00  2.4670549e-03 -5.3482020e-01
     5.9715688e-01]
   [ 7.2148931e-01 -8.5639261e-02  4.1533118e-01 -7.5208969e-02
     4.0